version: '3'
services:
  # can call this service whatever: node, web, etc.
  # this is our local application that we are building
  # the container name should ber the same as the mongo db instance you want to connect to in your app.
  # e.g. mongodb://mongo:27017/docker-node-mongo
  app:
    container_name: docker-node-mongo
    # if it fails always restart it
    restart: always
    # look for the docker file in the same dir as your current local one to build from
    build: .
    ports:
      # where 80 is local and 3000 is docker
      - '80:3000'
    # want to map our app service to our mongo service
    links:
      - mongo
  mongo:
    container_name: mongo
    # by defining the image, it will automatically pull from docker hub
    image: mongo
    ports:
      - '27107:27017'
